cbm:
  attr_weight: 1
  gamma: 0.7
  learning_rate: 0.001
  n_epochs: 25
  n_linear_output: 64
  two_layers: true
  activation: Sigmoid
cbm_res:
  attr_weight: 1
  gamma: 0.7
  learning_rate: 0.001
  n_epochs: 25
  n_linear_output: 64
  activation: Sigmoid
cbm_skip:
  attr_weight: 1
  gamma: 0.7
  learning_rate: 0.001
  n_epochs: 25
  n_hidden: 32
  n_linear_output: 64
  activation: Sigmoid
cnn:
  gamma: 0.7
  learning_rate: 0.001
  n_epochs: 25
  n_linear_output: 64
