cbm:
  attr_weight: 1
  attr_weight_decay: 1
  gamma: 0.7
  learning_rate: 0.005
  n_epochs: 30
  n_linear_output: 64
  two_layers: true
  activation: sigmoid
  dropout_probability: 0.2
cbm_res:
  attr_weight: 1
  attr_weight_decay: 1
  gamma: 0.7
  learning_rate: 0.005
  n_epochs: 30
  n_linear_output: 64
  activation: sigmoid
  dropout_probability: 0.2
cbm_skip:
  attr_weight: 1
  attr_weight_decay: 1
  gamma: 0.7
  learning_rate: 0.005
  n_epochs: 30
  n_hidden: 16
  n_linear_output: 64
  activation: sigmoid
  dropout_probability: 0.2
scm:
  attr_weight: 1
  attr_weight_decay: 1
  gamma: 0.7
  learning_rate: 0.005
  n_epochs: 30
  n_hidden: 16
  n_linear_output: 64
  activation: sigmoid
  dropout_probability: 0.2
cnn:
  gamma: 0.7
  learning_rate: 0.005
  n_epochs: 30
  n_linear_output: 64
  dropout_probability: 0.2
