name: hybrid_cbm
channels:
- defaults
dependencies:
- python=3.10.12
- numpy=1.25.2
- matplotlib=3.5.3
- pytorch=2.0.1
- torchvision=0.15.2
- scikit-learn=1.0.2
- pillow=10.2.0
- pyyaml=6.0.1
- pip
- pip:
  - optuna==3.3.0