cbm:
  activation: none
  attr_weight: 0.4939
  gamma: 0.945
  learning_rate: 0.0582
  n_epochs: 3
  n_linear_output: 34
  test_accuracy: 0
  two_layers: false
  val_loss: 1.7534
cbm_res:
  activation: relu
  attr_weight: 3.3632
  gamma: 0.6057
  learning_rate: 0.0001
  n_epochs: 3
  n_linear_output: 19
  test_accuracy: 0
  val_loss: 2.2361
cbm_skip:
  activation: relu
  attr_weight: 0.1202
  gamma: 0.6567
  learning_rate: 0.0382
  n_epochs: 3
  n_hidden: 67
  n_linear_output: 207
  test_accuracy: 0
  val_loss: 2.2337
cnn:
  gamma: 0.8738
  learning_rate: 0.0035
  n_epochs: 2
  n_linear_output: 159
  test_accuracy: 0
  val_loss: 1.9086
