cbm:
  activation: relu
  attr_weight: 5.525
  gamma: 0.6582
  learning_rate: 0.0001
  n_epochs: 2
  n_linear_output: 113
  test_acuracy: 7.1667
  test_set_accuracy: 0
  two_layers: false
cbm_res:
  activation: none
  attr_weight: 0.0233
  gamma: 0.9084
  learning_rate: 0.0004
  n_epochs: 3
  n_linear_output: 132
  test_acuracy: 7.3333
  test_set_accuracy: 0
cbm_skip:
  activation: sigmoid
  attr_weight: 0.0177
  gamma: 0.9012
  learning_rate: 0.0027
  n_epochs: 2
  n_hidden: 23
  n_linear_output: 120
  test_acuracy: 7.5
  test_set_accuracy: 0
cnn:
  gamma: 0.8979
  learning_rate: 0.0089
  n_epochs: 3
  n_linear_output: 31
  test_acuracy: 6.1667
  test_set_accuracy: 0
