cbm:
  activation: relu
  attr_weight: 0.075
  gamma: 0.5443
  learning_rate: 0.0
  n_epochs: 2
  n_linear_output: 32
  test_acuracy: 6.6667
  test_set_accuracy: 0
  two_layers: false
cbm_res:
  activation: relu
  attr_weight: 8.8512
  gamma: 0.6195
  learning_rate: 0.0066
  n_epochs: 1
  n_linear_output: 125
  test_acuracy: 8.6667
  test_set_accuracy: 0
cbm_skip:
  activation: sigmoid
  attr_weight: 0.0191
  gamma: 0.7154
  learning_rate: 0.0006
  n_epochs: 1
  n_hidden: 43
  n_linear_output: 219
  test_acuracy: 5.3333
  test_set_accuracy: 0
cnn:
  gamma: 0.6708
  learning_rate: 0.0142
  n_epochs: 1
  n_linear_output: 160
  test_acuracy: 8.0
  test_set_accuracy: 0
