cbm:
  activation: sigmoid
  attr_weight: 0.5208
  gamma: 0.6372
  learning_rate: 0.0001
  n_epochs: 2
  n_linear_output: 140
  test_acuracy: 5.3333
  test_set_accuracy: 0
  two_layers: true
cbm_res:
  activation: none
  attr_weight: 3.1717
  gamma: 0.6441
  learning_rate: 0.0
  n_epochs: 1
  n_linear_output: 198
  test_acuracy: 7.0
  test_set_accuracy: 0
cbm_skip:
  activation: relu
  attr_weight: 0.197
  gamma: 0.9387
  learning_rate: 0.0405
  n_epochs: 2
  n_hidden: 40
  n_linear_output: 40
  test_acuracy: 6.6667
  test_set_accuracy: 0
cnn:
  gamma: 0.9689
  learning_rate: 0.0097
  n_epochs: 2
  n_linear_output: 25
  test_acuracy: 8.6667
  test_set_accuracy: 0
