cbm:
  activation: sigmoid
  attr_weight: 0.5802
  gamma: 0.875
  learning_rate: 0.0067
  n_epochs: 3
  n_linear_output: 187
  test_acuracy: 6.0
  test_set_accuracy: 0
  two_layers: true
cbm_res:
  activation: sigmoid
  attr_weight: 3.3554
  gamma: 0.6734
  learning_rate: 0.0001
  n_epochs: 3
  n_linear_output: 30
  test_acuracy: 7.1111
  test_set_accuracy: 0
cbm_skip:
  activation: sigmoid
  attr_weight: 0.0609
  gamma: 0.6531
  learning_rate: 0.0001
  n_epochs: 3
  n_hidden: 9
  n_linear_output: 40
  test_acuracy: 8.6667
  test_set_accuracy: 0
cnn:
  gamma: 0.7705
  learning_rate: 0.0057
  n_epochs: 3
  n_linear_output: 252
  test_acuracy: 6.2222
  test_set_accuracy: 0
